# Generated by Django 4.2.2 on 2023-07-05 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0002_customuser_plan"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
