# Generated by Django 4.2.2 on 2023-07-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incorrectpayments",
            name="returned",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="payments",
            name="incorrect_payment",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_not_confirmed",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_not_confirmed_incorrect",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="payments",
            name="recived",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="payments",
            name="withdrawn",
            field=models.BooleanField(),
        ),
    ]
