# Generated by Django 4.2.2 on 2023-07-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0004_alter_incorrectpayments_returned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="recived",
            field=models.FloatField(),
        ),
    ]
