# Generated by Django 4.2.2 on 2023-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0006_payments_redirect_url_payments_signal_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="redirect_url",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="payments",
            name="signal_url",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
