# Generated by Django 4.2.2 on 2023-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0008_purchasedplans"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedplans",
            name="username",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
