# Generated by Django 4.2.2 on 2023-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0011_rename_username_purchasedplans_username_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="recived_unconfirmed",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
