# Generated by Django 4.2.2 on 2023-08-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0012_payments_recived_unconfirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="tx_confirmations",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
