# Generated by Django 4.2.2 on 2023-08-30 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0013_payments_tx_confirmations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="remaining_days_plan",
            new_name="remaining_minutes_plan",
        ),
    ]
